### ISSUE TITLE
Updating a book doesnt reindex the terms

### ISSUE THREAD

**Issue by RamSury** [jzohrab/lute-v3#108] opened 2024-01-03 12:10 UTC
**Description**

After updating a book with new content (i.e. adding or changing a book's content) - clicking on 'Sentences' link from a term does not bring up the updated content.

**To Reproduce**

Steps to reproduce the behavior, e.g.:

1. Update a book by adding new content
2. Click on a term added newly (assuming the term already exists)
3. Click on the 'Sentences' link to view the sentences it is used in
4. The newly added sentences do not show (as they have probably not been indexed)

**Screenshots**

N.A.

**Extra software info, if not already included in the Description:**

- OS (e.g., iOS, windows): Windows
- Browser (e.g., chrome, safari): Firefox & Chrome
- How you've installed Lute (Docker, python, source): Python
- Version: 3.0.8

**Comment by jzohrab** [comment] 2024-01-03 13:09
Hi @RamSury - thanks for opening this.  This is by design -- The sentences aren't shown until a page is marked as "read" -- ref https://jzohrab.github.io/lute-manual/faq/sentences-only-shown-when-page-is-read.html  Let me know if that's not clear, or if you expected something different.  I think this design decision is good.

**Comment by RamSury** [comment] 2024-01-04 14:35
Yes, it works if the book is marked read. Thanks.

**Comment by jzohrab** [comment] 2024-01-04 14:39
Cheers, will close.  Thanks!

**Closed by jzohrab** 2024-01-04 14:39 UTC
Labels: question
