### ISSUE TITLE
Popup gets stuck sometimes.

### ISSUE THREAD

**Issue by shetozz** [jzohrab/lute-v3#109] opened 2024-01-04 09:53 UTC
**Description**

When saving a change in a term, if you move the cursor to another term that has a popup, it -the popup- gets stuck.

**To Reproduce**
1. Hover a term that has a popup.
2. Select another term.
3. Click `save` on the new term.
4. Move your cursor before the page updates to a term that has a popup
5. The popup will stay till you reload again.
6.  Sometimes the popup appears in a random position -screenshot-, but I don't know the condition of re-producing this specific one.

**Screenshots**
* [Screencast from 2024-01-04 11-39-22.webm](https://github.com/jzohrab/lute-v3/assets/93838524/39b98ee0-d567-4ffc-aa6a-0f0b6c165e99)

***
![Screenshot from 2024-01-04 11-40-03](https://github.com/jzohrab/lute-v3/assets/93838524/ee409fe9-7038-49e8-86ed-0dde70a4037a)

**Extra software info, if not already included in the Description:**
> Lute versions this happened in:
> v3.07, v3.08, dev branch, and fangyingfx's branch with the Mandarin parser.
- OS (e.g., iOS, windows):
 > Fedora 39 workstation edition.
- Browser (e.g., chrome, safari):
 > Firefox, Brave.
- How you've installed Lute (Docker, python, source)
 > pip

**Comment by jzohrab** [comment] 2024-01-04 10:21
Well then, don't do that!  :-P

I thought this had been fixed ... I haven't seen it lately, but granted I've been doing work on Lute rather than using it, so it could still be there.  Thanks for the issue!

**Comment by shetozz** [comment] 2024-01-04 10:33
> Well then, don't do that! :-P

That's the workaround I'm trying to use.

**Comment by fanyingfx** [comment] 2024-01-04 10:43
I found it could reproduce on Japanese and can't reproduce on English, maybe releated to the pronunciation field?


https://github.com/jzohrab/lute-v3/assets/57335844/2385cf69-67d9-45e2-b5c8-ab7d02c4d085

**Comment by fanyingfx** [comment] 2024-01-04 11:08
Sorry, It could also happen on English, seems not related to pronunciation field.

**Comment by jzohrab** [comment] 2024-02-02 11:27
Reproduced on `develop`, but it's hard to do.

> <img width="25%" alt="image" src="https://github.com/jzohrab/lute-v3/assets/1637133/cbf827d3-74a0-454d-9e17-61b6de00f23c">

**Comment by jzohrab** [comment] 2024-02-02 11:57
Reproduced and tried a few hacks to fix it, but didn't work.  :-/

**Comment by jamesdeluk** [comment] 2024-02-20 21:16
Also have this issue.

If you Save _any_ term, the popup disappears. So I guess it might be related to saving? It's also a workaround without having to reload the entire page.

**Comment by shetozz** [comment] 2024-02-20 21:17
A save refreshes the page AFAIK.

**Comment by jzohrab** [comment] 2024-03-02 02:45
I'm no longer able to reproduce this after several tries -- there have been a few changes with the events that may have fixed this.  I'll close it, and if it happens again LMK.  Cheers!

**Closed by jzohrab** 2024-03-02 02:45 UTC
Labels: bug, UI
